version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ticketdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_ai
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket_ai"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: